# Generated by Django 5.2.11 on 2026-02-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_tenant__20c46c_idx',
            old_name='bookings_bo_tenant__651c5d_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_status_f6e1f8_idx',
            old_name='bookings_bo_status_d505ba_idx',
        ),
    ]
