services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  django:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: /app/entrypoint.sh gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: celery -A config worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - django
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: celery -A config beat -l info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - django
      - redis

  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: python bot/main.py
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - django
      - redis

volumes:
  postgres_data:
