# Generated by Django 5.2.11 on 2026-02-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='service',
            new_name='services_se_tenant__c48253_idx',
            old_name='services_se_tenant__8fbccf_idx',
        ),
        migrations.RenameIndex(
            model_name='staff',
            new_name='services_st_tenant__8b40cb_idx',
            old_name='services_st_tenant__f6f634_idx',
        ),
    ]
