# Generated by Django 5.2.11 on 2026-02-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_tenant__731b87_idx',
            old_name='accounts_use_tenant__677e52_idx',
        ),
    ]
